language: node_js
sudo: false
node_js:
- lts/*
install:
- npm install
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_b2a93f9bb546_key -iv $encrypted_b2a93f9bb546_iv
  -in travis-ci.enc -out travis-ci -d
