version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:latest # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands 
      - checkout # special step to check out source code to working directory
      - run:
          name: Update NPM 
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Packages
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run build
          name: Build
          command: npm run build
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Export Tag
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
      - run:
          name: Push Docker Image
          command: |
            docker build -t $DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:$TAG
      - run:
          name: Deploy To Digital Ocean
          command: |
            ssh -o StrictHostKeyChecking=no circle-ci@smartgoalsapp.ml "/bin/bash ./deploy_app.sh $DOCKER_REPO_NAME/$DOCKER_IMAGE_NAME:$TAG"