swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "v1"
  title: REST API for 'The Smart Goals App'
  description: |
    The is a demo Swagger Spec for the sample REST API used by The Smart Goals App that Maksym Lapshyn developed as part of his [Make Software Engineering Great Again](https://9gag.com/) campaign.
    
host: localhost:3000
basePath: /api

schemes:
  - http

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string